export interface PokemonTeam {
    id?:number | null,
    id_pokemon?:number | null,
    move_1?:number | null,
    move_2?:number | null,
    move_3?:number | null,
    move_4?:number | null,
    ability?:number | null,
    item?:number | null,
    iv_atk?:number | null,
    iv_spatk?:number | null,
    iv_def?:number | null,
    iv_spdef?:number | null,
    iv_spd?:number | null,
    iv_hp?:number | null,
    ev_atk?:number | null,
    ev_spatk?:number | null,
    ev_def?:number | null,
    ev_spdef?:number | null,
    ev_spd?:number | null,
    ev_hp?:number | null,
    is_shiny?:boolean | null,
    tera_type?:number | null,
    level?:number | null
}
