export interface PokemonTeam {
<<<<<<< HEAD
    id?:number | null,
    id_pokemon?:number | null,
    move_1?:number | null,
    move_2?:number | null,
    move_3?:number | null,
    move_4?:number | null,
    ability?:number | null,
    item?:number | null,
    iv_atk?:number | null,
    iv_spatk?:number | null,
    iv_def?:number | null,
    iv_spdef?:number | null,
    iv_spd?:number | null,
    iv_hp?:number | null,
    ev_atk?:number | null,
    ev_spatk?:number | null,
    ev_def?:number | null,
    ev_spdef?:number | null,
    ev_spd?:number | null,
    ev_hp?:number | null,
    is_shiny?:boolean | null,
    tera_type?:number | null,
    level?:number | null
=======
    id:number,
    id_pokemon:number,
    move_1:number,
    move_2:number,
    move_3:number,
    move_4:number,
    ability:number,
    item:number,
    iv_atk:number,
    iv_spatk:number,
    iv_def:number,
    iv_spdef:number,
    iv_spd:number,
    iv_hp:number,
    ev_atk:number,
    ev_spatk:number,
    ev_def:number,
    ev_spdef:number,
    ev_spd:number,
    ev_hp:number,
    is_shiny:boolean,
    tera_type:number,
    level:number
>>>>>>> b305fe81c8d3ca6dac897524b65c84cc5796ad4f
}
